### PR TITLE
Introduce GitHub CI workflow

### PR DESCRIPTION
**Pull request by drakulavich**
Check the build with multiple dotnet versions

### CODE REVIEW

**Comment by drakulavich** [comment]
Maybe it's the time: https://techcrunch.com/2023/01/05/circleci-breach/

**Comment by basdijkstra** [comment]
Cheers Anton! I'll have a look very soon. I've been meaning to move to GitHub CI anyway, to make it easier for others to build and contribute. The breach you're referring to is good motivation to take action.

**Comment by basdijkstra** [comment]
Hey @drakulavich, looks good, but could you please change the version matrix to

`['3.1.x', '6.0.x', '7.0.x']`

?

Those are the .NET versions I currently support.

I'll remove support for .NET Core 3.1 soon anyway as that is [no longer supported by Microsoft](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), but that'll be a separate action, and I don't know when I'll do that exactly. For now, I want to migrate CI systems without touching changing anything in .NET versions.

Thanks!

**Comment by drakulavich** [comment]
Sure! I fixed the version matrix.

**Pull request merged**
