### PR TITLE
Feature/headers in requestspec

### PR DESCRIPTION
**Pull request by basdijkstra**
This PR adds the capability to:

* Specify headers in a request specification
* Specify Basic and OAuth2 authorization details in a request specification

### CODE REVIEW

**Comment by bheemreddy181** [comment]
You are only adding Basic and Oauth2 headers on request specification why not other headers like Authorization header or a content type header etc ?

**Comment by bheemreddy181** [comment]
Technically request specification should have ability for all headers like a regular test can add

**Comment by basdijkstra** [comment]
You've got a point about the `Content-Type` header, I'll add that as a separate issue. Authorization _is_ Basic and OAuth2.

**Comment by bheemreddy181** [comment]
@basdijkstra would you like to support all the Auth types ? I am pretty pulling them up from postman 
Screen Shot 2022-11-11 at 11 16 34 AM

**Comment by basdijkstra** [comment]
I’m not planning to support authentication schemes just ‘because Postman does it’.

I’m obviously happy to add support for additional schemes, if people have a use case for it.

**Pull request merged**
